// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Agent = { name: string, host: string, cwd: string, sessionId: string | null, online: boolean, isHuman: boolean, version: string | null, 
/**
 * Epoch milliseconds.
 *
 * `#[ts(type = "number")]` rather than ts-rs's default `bigint` for i64:
 * serde emits a JSON number, so `JSON.parse` yields a JavaScript number and
 * a `bigint` type would be a lie the first consumer trips over. The
 * precision caution behind that default does not apply — epoch millis are
 * ~1.8e12, far below Number.MAX_SAFE_INTEGER.
 */
lastSeen: number, };
