// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatusView } from "./StatusView";

export type AgentInfo = { name: string, host: string, online: boolean, 
/**
 * The agent's reported crate version, or `None` for a binary predating the field.
 */
version: string | null, 
/**
 * `None` when the agent has never reported a status, or when a bus that
 * predates statuses answered.
 */
status: StatusView | null, };
