// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentInfo = { name: string, host: string, online: boolean, 
/**
 * The agent's reported crate version, or `None` for a binary predating the field.
 */
version: string | null, };
