// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentRoomSummary = { name: string, messageCount: number, 
/**
 * Epoch milliseconds; 0 when the agent has sent nothing in this room.
 */
lastActivity: number, };
