// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentEventItem = { id: number, kind: string, detail: unknown, createdAt: number, };
