// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEventItem } from "./AgentEventItem";
import type { AgentRoomSummary } from "./AgentRoomSummary";

export type AgentDetail = { name: string, host: string, cwd: string, sessionId: string | null, version: string | null, online: boolean, isHuman: boolean, lastSeen: number, 
/**
 * Twenty five-minute slots, oldest first — the detail strip's width.
 */
buckets: number[], rooms: Array<AgentRoomSummary>, events: Array<AgentEventItem>, 
/**
 * The true count, not `events.len()`.
 */
eventTotal: number, };
