// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an agent is doing, as its Claude Code hooks last reported it.
 *
 * `Unknown` is a real state, not a missing value: a session without the hooks
 * installed, or one that has not fired a hook since it started.
 */
export type AgentState = "working" | "idle" | "blocked_on_human" | "unknown";
