// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeletionPreview = { 
/**
 * 1 when the agent row exists, 0 otherwise — the modal states it as a count
 * beside the others rather than as a special case.
 */
registration: number, memberships: number, cursors: number, 
/**
 * For the modal's "on buildbox" clause.
 */
host: string, 
/**
 * Decides whether the dialog opens confirmable or refused. The server
 * re-checks this at delete time regardless; this is for rendering.
 */
online: boolean, };
