// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Event = { id: number, kind: string, agent: string | null, room: string | null, detail: unknown, createdAt: number, };
