// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplyResult } from "./ReplyResult";
import type { RoomUnread } from "./RoomUnread";

/**
 * bus → agent
 *
 * `ts_rs::TS` is derived here, not only on the REST DTOs in `web::api`, and
 * that asymmetry was the root cause of three separate bugs in one phase. The
 * push protocol is snake_case on the wire — `rename_all` on an enum renames
 * variant *names*, not variant *fields* — while the DTOs are camelCase, and
 * every browser-side handler was a cast against a hand-written literal, which
 * is the one construct that silences the compiler about exactly this. With the
 * union generated, a rename in this file breaks the TypeScript build instead of
 * producing a silent `undefined` that passes every gate.
 */
export type FromBus = { "type": "registered", name: string, 
/**
 * Whether this connection holds a relayer grant — its sends are stamped with
 * its human's authority (`human="true"`).
 *
 * The bus is the only party that knows: the grant lives in configuration, and
 * `Relayers::contains` matches the effective name, so a renamed collision holds
 * no grant. Without this field an agent can only infer its own provenance from
 * instructions that say `human="false"` means "another agent sent this" — right
 * for every agent except a relayer, which is exactly the one that cannot tell.
 *
 * Absent on the wire means `false`, for the same reason `Register::human` has a
 * default: Claude Code spawns a stdio MCP server once at session start and never
 * respawns it, so a client that predates a new bus keeps parsing this frame.
 */
relayer: boolean, } | { "type": "observing", name: string, } | { "type": "reply", req_id: number, result: ReplyResult, } | { "type": "message", id: number, room: string, from: string, text: string, done: boolean, 
/**
 * Set by the bus from the sending connection, never by the sender. Absent on
 * the wire means `false` so an agent binary that predates this field keeps
 * deserializing — the same constraint that governs `Register.human`.
 */
human: boolean, } | { "type": "unread", rooms: Array<RoomUnread>, } | { "type": "paused", room: string, reason: string, } | { "type": "error", req_id: number | null, message: string, } | { "type": "presence", name: string, host: string, online: boolean, last_seen: number, } | { "type": "event", id: number, kind: string, agent: string | null, room: string | null, detail: unknown, created_at: number, };
