// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryItem = { id: number, from: string, text: string, done: boolean, created_at: number, 
/**
 * Whether a human sent this. Carried on history as well as on the live event
 * because a worker that was offline catches up through `history` — the reconnect
 * path sends only an `Unread` summary, never a replay.
 */
human: boolean, };
