// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Message = { id: number, room: string, from: string, body: string, done: boolean, 
/**
 * True when the sender carried human authority — a person, or a configured
 * relayer speaking for one.
 */
human: boolean, createdAt: number, };
