// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Meta = { 
/**
 * The host the bus itself is running on. Half of the top bar's pill
 * ("hardac · 0.3.3") — the reason this endpoint exists.
 */
host: string, version: string, };
