// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RailMessage } from "./RailMessage";
import type { RoomFlagDto } from "./RoomFlagDto";

export type RailRoom = { name: string, members: Array<string>, lastActivity: number | null, 
/**
 * Twelve five-minute slots, oldest first.
 */
buckets: Array<number>, flag: RoomFlagDto | null, hidden: boolean, 
/**
 * The room's most recent message, for the console inbox. `None` for a room
 * with no messages.
 */
lastMessage: RailMessage | null, };
