// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RailAgent } from "./RailAgent";
import type { RailRoom } from "./RailRoom";

export type RailSummary = { rooms: Array<RailRoom>, agents: Array<RailAgent>, };
