// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomFlagDto } from "./RoomFlagDto";

export type RailRoom = { name: string, members: Array<string>, lastActivity: number | null, 
/**
 * Twelve five-minute slots, oldest first.
 */
buckets: Array<number>, flag: RoomFlagDto | null, hidden: boolean, };
