// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RailAgent = { name: string, host: string, version: string | null, online: boolean, isHuman: boolean, 
/**
 * See `Agent::is_relayer`.
 */
isRelayer: boolean, lastSeen: number, buckets: Array<number>, };
