// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RailMessage = { from: string, 
/**
 * One line, at most `EXCERPT_CAP` characters. Verbatim apart from that:
 * escaping is the renderer's job.
 */
excerpt: string, 
/**
 * The message carried human authority (a person, or a configured relayer).
 */
human: boolean, };
