// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A room's derived state for the rail. Data, not sentences: the client composes
 * the subtitle, because the handoff specifies copy as final and design-owned.
 *
 * `rename_all_fields` (in addition to `rename_all`, which only renames the
 * variant names) is required here: without it `waiting_on` ships on the wire
 * unrenamed, silently breaking the "camelCase on the wire" rule the rest of
 * this module holds to — `rename_all` on an enum does not reach into its
 * variants' fields.
 */
export type RoomFlagDto = { "kind": "needsYou", exchanges: number, } | { "kind": "blocked", queued: number, waitingOn: Array<string>, };
