// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stored file in a room.
 *
 * Deliberately not `proto::FileInfo`, which is the websocket protocol's shape
 * and therefore snake_case on the wire. Every `/api` response is camelCase, and
 * reusing the protocol type would put one snake_case object into an otherwise
 * camelCase surface — the drift this module's header exists to prevent.
 */
export type RoomFile = { key: string, size: number, contentType: string | null, updatedBy: string, 
/**
 * Epoch milliseconds.
 */
updatedAt: number, };
