// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One room's contribution to a reconnecting agent's `FromBus::Unread`
 * summary.
 */
export type RoomUnread = { room: string, count: number, };
