// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentState } from "./AgentState";

/**
 * An agent's status as readers see it. Every time is bus time, epoch milliseconds.
 */
export type StatusView = { state: AgentState, since: number, last_heartbeat: number | null, reason: string | null, text: string | null, text_at: number | null, 
/**
 * Working, but no hook has fired for longer than the quiet threshold. A soft
 * hint, not a verdict: one long Bash command fires no hooks while it runs.
 */
quiet: boolean, };
